name: Main

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: knownothinnobody/github-br-merge-action@v1.0.4
        with:
          token: ${{ secrets.AUTH_TOKEN }}
