name: Main

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != true
        run: npm i

      - uses: knownothinnobody/github-br-merge-action@v1.0.0
        with:
          token: ${{ secrets.AUTH_TOKEN }}
